### ISSUE TITLE
IE11 issue with nextTick

### ISSUE THREAD

**Issue by AkiraLaine** [pagekit/vue-resource#567]
Original issue: https://github.com/vuejs/vue/issues/5031

It seems that with the new Vue 2.2.x update, Vue Resource crashes when using `nextTick`. This might be related to the fact that Vue removed many exposed methods on Vue.util?

![image](https://cloud.githubusercontent.com/assets/11958359/23387936/93d8c836-fdb3-11e6-841e-d7557bfcd780.png)

**Comment by ozee31** [comment]
I have the same problem

**Comment by steffans** [comment]
Fixed in v1.2.1

**Comment by ozee31** [comment]
👍

**Comment by leson** [comment]
so fast response, nice. and many thanks!

**Comment by alexcheninfo** [comment]
I'm still getting the error in this line:

```
function nextTick(cb, ctx) {
    return ntick(cb, ctx);
}
```
I'm using vue-resource 1.2.1 an Vue 2.2.2. IE 11 on Windows 7.

**Comment by bibiseb** [comment]
I updated to version 1.2.1 the error I get now is :

```
function nextTick(cb, ctx) {
    return ntick(cb, ctx);
    /*Object expected*/
}
```

in vue-resource.common.js on line 296

**Comment by vintage** [comment]
@bibiseb What code triggers this error? I've just had same problem and updating to 1.2.1 resolved it (works on IE11).

**Comment by bibiseb** [comment]
I am using onsen ui on a project and it seems that the problem could be a conflict with that library. Vue and Vue-resource are successfully working when I don't use that UI library.

**Comment by sean-hill** [comment]
I'm facing this same issue using `vue-resource` version `1.3.4`.

![screen shot 2018-02-15 at 3 47 37 pm](https://user-images.githubusercontent.com/1205866/36285110-94997f44-1267-11e8-8da9-94814c11447a.png)
![screen shot 2018-02-15 at 3 46 32 pm](https://user-images.githubusercontent.com/1205866/36285113-95e5d76c-1267-11e8-9fa5-e65a33387599.png)

**Comment by brickgale** [comment]
facing this issue version `1.3.4` too.
